// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/backup.dart';
import 'api/data/db.dart';
import 'api/data/logging.dart';
import 'api/integrations/public_traits.dart';
import 'api/integrations/traits.dart';
import 'api/main.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<RustLogRecord> dco_decode_StreamSink_rust_log_record_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MessageDestination dco_decode_box_autoadd_message_destination(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  DestinationKind dco_decode_destination_kind(dynamic raw);

  @protected
  DestinationTestResult dco_decode_destination_test_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IntegrationAccount dco_decode_integration_account(dynamic raw);

  @protected
  IntegrationGradient dco_decode_integration_gradient(dynamic raw);

  @protected
  IntegrationInfo dco_decode_integration_info(dynamic raw);

  @protected
  IntegrationProvider dco_decode_integration_provider(dynamic raw);

  @protected
  List<IntegrationAccount> dco_decode_list_integration_account(dynamic raw);

  @protected
  List<IntegrationInfo> dco_decode_list_integration_info(dynamic raw);

  @protected
  List<MessageDestination> dco_decode_list_message_destination(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MessageDestination dco_decode_message_destination(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  RustLogRecord dco_decode_rust_log_record(dynamic raw);

  @protected
  SentMessage dco_decode_sent_message(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<RustLogRecord> sse_decode_StreamSink_rust_log_record_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MessageDestination sse_decode_box_autoadd_message_destination(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  DestinationKind sse_decode_destination_kind(SseDeserializer deserializer);

  @protected
  DestinationTestResult sse_decode_destination_test_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IntegrationAccount sse_decode_integration_account(
    SseDeserializer deserializer,
  );

  @protected
  IntegrationGradient sse_decode_integration_gradient(
    SseDeserializer deserializer,
  );

  @protected
  IntegrationInfo sse_decode_integration_info(SseDeserializer deserializer);

  @protected
  IntegrationProvider sse_decode_integration_provider(
    SseDeserializer deserializer,
  );

  @protected
  List<IntegrationAccount> sse_decode_list_integration_account(
    SseDeserializer deserializer,
  );

  @protected
  List<IntegrationInfo> sse_decode_list_integration_info(
    SseDeserializer deserializer,
  );

  @protected
  List<MessageDestination> sse_decode_list_message_destination(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MessageDestination sse_decode_message_destination(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  RustLogRecord sse_decode_rust_log_record(SseDeserializer deserializer);

  @protected
  SentMessage sse_decode_sent_message(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_rust_log_record_Sse(
    RustStreamSink<RustLogRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_message_destination(
    MessageDestination self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_destination_kind(
    DestinationKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_destination_test_result(
    DestinationTestResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_integration_account(
    IntegrationAccount self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_integration_gradient(
    IntegrationGradient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_integration_info(
    IntegrationInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_integration_provider(
    IntegrationProvider self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_integration_account(
    List<IntegrationAccount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_integration_info(
    List<IntegrationInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_destination(
    List<MessageDestination> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_destination(
    MessageDestination self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_rust_log_record(RustLogRecord self, SseSerializer serializer);

  @protected
  void sse_encode_sent_message(SentMessage self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
