// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/backup.dart';
import 'api/data/db.dart';
import 'api/integrations/traits.dart';
import 'api/main.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  IntegrationChannel dco_decode_integration_channel(dynamic raw);

  @protected
  IntegrationGradient dco_decode_integration_gradient(dynamic raw);

  @protected
  IntegrationInfo dco_decode_integration_info(dynamic raw);

  @protected
  IntegrationTestResult dco_decode_integration_test_result(dynamic raw);

  @protected
  IntegrationUser dco_decode_integration_user(dynamic raw);

  @protected
  List<IntegrationChannel> dco_decode_list_integration_channel(dynamic raw);

  @protected
  List<IntegrationInfo> dco_decode_list_integration_info(dynamic raw);

  @protected
  List<IntegrationUser> dco_decode_list_integration_user(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  IntegrationChannel sse_decode_integration_channel(
    SseDeserializer deserializer,
  );

  @protected
  IntegrationGradient sse_decode_integration_gradient(
    SseDeserializer deserializer,
  );

  @protected
  IntegrationInfo sse_decode_integration_info(SseDeserializer deserializer);

  @protected
  IntegrationTestResult sse_decode_integration_test_result(
    SseDeserializer deserializer,
  );

  @protected
  IntegrationUser sse_decode_integration_user(SseDeserializer deserializer);

  @protected
  List<IntegrationChannel> sse_decode_list_integration_channel(
    SseDeserializer deserializer,
  );

  @protected
  List<IntegrationInfo> sse_decode_list_integration_info(
    SseDeserializer deserializer,
  );

  @protected
  List<IntegrationUser> sse_decode_list_integration_user(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_integration_channel(
    IntegrationChannel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_integration_gradient(
    IntegrationGradient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_integration_info(
    IntegrationInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_integration_test_result(
    IntegrationTestResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_integration_user(
    IntegrationUser self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_integration_channel(
    List<IntegrationChannel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_integration_info(
    List<IntegrationInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_integration_user(
    List<IntegrationUser> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
