// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `database_path`, `db`

/// Returns the database name (with extension).
Future<String> getDatabaseName() =>
    RustLib.instance.api.crateApiDataDbGetDatabaseName();

/// Initialize the application database.
///
/// Must be called exactly once during app startup.
Future<void> initDatabase({required String path}) =>
    RustLib.instance.api.crateApiDataDbInitDatabase(path: path);

/// Return the database path as a string.
Future<void> databasePathStr() =>
    RustLib.instance.api.crateApiDataDbDatabasePathStr();

/// Open connection to application database.
///
/// Opens the database located at the configured database path and stores
/// it in the global database instance.
///
/// # Errors
///
/// Returns an error if:
///
/// - the database file cannot be opened
/// - SQLite initialization fails
Future<void> openDatabase() =>
    RustLib.instance.api.crateApiDataDbOpenDatabase();

/// Close connection to application database.
///
/// After calling this function, any attempt to access the database
/// must first reopen it using [`open_database`].
///
/// Closing the database is required before replacing the underlying
/// database file during an import operation.
///
/// Calling this function multiple times is safe.
///
/// # Errors
///
/// Returns an error if SQLite fails to close the connection.
Future<void> closeDatabase() =>
    RustLib.instance.api.crateApiDataDbCloseDatabase();

/// Export the application database.
///
/// Performs a consistent export of the current SQLite database by:
///
/// 1. Performing a WAL checkpoint.
/// 2. Copying the database file.
///
/// The database connection remains open during the export.
///
/// # Arguments
///
/// * `path` - Destination path of the exported database.
///
/// # Errors
///
/// Returns an error if the checkpoint or file copy fails.
///
/// # Notes
///
/// This function only exports the SQLite database.
///
/// Metadata generation and ZIP creation should be handled by
/// higher-level backup functions.
Future<void> exportDatabase({required String path}) =>
    RustLib.instance.api.crateApiDataDbExportDatabase(path: path);

/// Import a SQLite database.
///
/// Replaces the current application database with an imported one.
///
/// The import procedure is:
///
/// 1. Close the current database.
/// 2. Replace the database file.
/// 3. Reopen the database.
///
/// # Arguments
///
/// * `path` - Path to the imported database.
///
/// # Errors
///
/// Returns an error if:
///
/// - the current database cannot be closed
/// - the database file cannot be copied
/// - the imported database cannot be opened
///
/// # Warning
///
/// The imported database completely replaces the existing one.
///
/// Existing data cannot be recovered unless a backup exists.
Future<void> importDatabase({required String path}) =>
    RustLib.instance.api.crateApiDataDbImportDatabase(path: path);

/// Delete the existing SQLite database.
Future<void> purgeDatabase() =>
    RustLib.instance.api.crateApiDataDbPurgeDatabase();

/// Returns a single row.
///
/// Returns `None` if no matching row exists.
Future<String> selectOne({required String sql}) =>
    RustLib.instance.api.crateApiDataDbSelectOne(sql: sql);

/// Returns JSON with data of multiple rows.
///
/// # Example
///
/// ```rust
/// let users = db.select(
///     "SELECT id, name FROM users WHERE name LIKE %?%"
/// )?;
/// ```
///
/// Returns:
///
/// ```json
/// [
///   { "id": 2, "name": "Mark" },
///   { "id": 5, "name": "Denmark" }
/// ]
/// ```
///
/// Usage in Dart:
///
/// ```dart
/// import 'dart:convert';
/// (...)
/// String jsonStr = await select(...);
/// List<dynamic> data = jsonDecode(jsonStr);
/// String name = data[0]['name'];
/// ```
Future<String> select({required String sql}) =>
    RustLib.instance.api.crateApiDataDbSelect(sql: sql);

/// Execute a SQL statement.
Future<BigInt> executeSql({required String sql}) =>
    RustLib.instance.api.crateApiDataDbExecuteSql(sql: sql);

/// Execute multiple SQL statements.
///
/// Example:
///
/// ```rust
/// db.execute_batch(
///     "
///     CREATE TABLE users (
///         id INTEGER PRIMARY KEY,
///         name TEXT NOT NULL
///     );
///
///     CREATE INDEX idx_users_name
///     ON users(name);
///     "
/// )?;
/// ```
Future<void> executeBatchSql({required String sql}) =>
    RustLib.instance.api.crateApiDataDbExecuteBatchSql(sql: sql);
