// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `database_path`, `db`

/// Returns the database name (with extension).
Future<String> getDatabaseName() =>
    RustLib.instance.api.crateApiDataDbGetDatabaseName();

/// Initialize the application database.
///
/// Must be called exactly once during app startup.
Future<void> initDatabase({required String path}) =>
    RustLib.instance.api.crateApiDataDbInitDatabase(path: path);

/// Return the database path as a string.
Future<void> databasePathStr() =>
    RustLib.instance.api.crateApiDataDbDatabasePathStr();

/// Delete the existing SQLite database.
Future<void> purgeDatabase() =>
    RustLib.instance.api.crateApiDataDbPurgeDatabase();
