// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear_sink`, `get_sink`, `new`, `set_sink`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RustLogger`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `enabled`, `flush`, `fmt`, `log`

/// Creates the Rust -> Dart logging stream.
///
/// FRB keeps the underlying StreamSink alive after this function returns.
Stream<RustLogRecord> createRustLogStream() =>
    RustLib.instance.api.crateApiDataLoggingCreateRustLogStream();

/// Disconnect the Rust -> Dart logging stream.
Future<void> disposeRustLogStream() =>
    RustLib.instance.api.crateApiDataLoggingDisposeRustLogStream();

/// A Rust log record transported to Dart.
///
/// This is deliberately a normal public FRB type. The FRB code generator
/// will generate the SSE serialization implementation for it.
class RustLogRecord {
  /// Unix timestamp in milliseconds when Rust created the record.
  final PlatformInt64 timeMillis;

  /// ERROR, WARN, INFO, DEBUG, TRACE.
  final String level;

  /// Rust log target, e.g. "my_crate::network".
  final String target;

  /// Rust module path.
  final String? modulePath;

  /// Rust source file.
  final String? file;

  /// Rust source line.
  final int? line;

  /// Actual log message.
  final String message;

  const RustLogRecord({
    required this.timeMillis,
    required this.level,
    required this.target,
    this.modulePath,
    this.file,
    this.line,
    required this.message,
  });

  @override
  int get hashCode =>
      timeMillis.hashCode ^
      level.hashCode ^
      target.hashCode ^
      modulePath.hashCode ^
      file.hashCode ^
      line.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustLogRecord &&
          runtimeType == other.runtimeType &&
          timeMillis == other.timeMillis &&
          level == other.level &&
          target == other.target &&
          modulePath == other.modulePath &&
          file == other.file &&
          line == other.line &&
          message == other.message;
}
