// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Application theme selection.
///
/// This enum represents the currently selected UI theme.
///
/// Responsibilities:
/// - Define available themes.
/// - Convert database values to enum variants.
/// - Persist and load the selected theme.
///
/// Non-responsibilities:
/// - Theme colors.
/// - Material Design configuration.
/// - Flutter UI styling.
///
/// Color palettes are defined in Dart, where each theme is mapped
/// to a Material 3 `ColorScheme`.
enum CustomTheme {
  default_,
  dracula,
  alucard,
  solarized,
  nord,
  monokai,
  gruvbox,
  catppuccinLatte,
  catppuccinFrappe,
  catppuccinMacchiato,
  catppuccinMocha;

  /// Convert a persisted theme label into a theme variant.
  ///
  /// Unknown values fall back to `CustomTheme::DefaultDark`.
  ///
  /// # Examples
  ///
  /// ```rust
  /// let theme = Theme::from_label("Nord");
  /// assert_eq!(theme, Theme::Nord);
  /// ```
  static Future<CustomTheme> fromLabel({required String s}) =>
      RustLib.instance.api.crateApiDataThemeCustomThemeFromLabel(s: s);

  /// Human-readable theme name.
  ///
  /// Returns a stable string representation of the theme.
  Future<String> label() =>
      RustLib.instance.api.crateApiDataThemeCustomThemeLabel(that: this);

  ///Get the current theme label from database
  ///
  /// Load the currently selected theme from the application database.
  ///
  /// The value is read from the `settings` table using the
  /// `theme` setting key.
  ///
  /// # Panics
  ///
  /// Panics if:
  /// - The database cannot be opened.
  /// - The query fails.
  /// - The setting does not exist.
  static Future<String> load() =>
      RustLib.instance.api.crateApiDataThemeCustomThemeLoad();

  /// Persist the selected theme to the application database.
  ///
  /// The theme label is stored in the `settings` table under
  /// the `theme` setting key.
  ///
  /// # Panics
  ///
  /// Panics if:
  /// - The database cannot be opened.
  /// - The update operation fails.
  static Future<void> save({required String label}) =>
      RustLib.instance.api.crateApiDataThemeCustomThemeSave(label: label);
}
