package com.appsbyrafa.stillalive

import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.os.Build
import androidx.core.app.NotificationCompat

/**
 * Creates and delivers Android notifications for the StillAlive application.
 *
 * This class encapsulates all notification-related Android APIs, including:
 *
 * - Notification channels.
 * - Notification priorities.
 * - Normal notifications.
 * - Silent notifications.
 * - Full-screen notifications.
 * - Alarm notifications.
 * - Notification interaction behavior such as auto-cancellation and
 *   ongoing state.
 *
 * Flutter requests notifications through [MainActivity], which forwards
 * the arguments to [send].
 *
 * [AlarmReceiver] uses [sendAlarm] for notifications generated by
 * Android's alarm system.
 *
 * ```
 * Flutter
 *     ↓
 * MainActivity
 *     ↓
 * NotificationSender
 *     ↓
 * NotificationManager
 * ```
 *
 * @param context Android context used to access notification system
 * services and application resources.
 */
class NotificationSender(
    private val context: Context
) {

    companion object {
        /**
         * Notification channel used by normal notifications.
         */
        const val NORMAL_CHANNEL_ID = "normal_notification_channel"

        /**
         * Notification channel used by full-screen notifications.
         */
        const val FULL_SCREEN_CHANNEL_ID = "full_screen_notification_channel"

        /**
         * Notification channel used by silent notifications.
         */
        const val SILENT_CHANNEL_ID = "silent_notification_channel"

        /**
         * Default notification identifier used when Flutter does not
         * provide one.
         */
        const val DEFAULT_NOTIFICATION_ID = 2000

        /**
         * Notification identifier used for the active alarm notification.
         *
         * This value is shared with [FullScreenIntentHandler] so that the
         * alarm notification can be dismissed after the full-screen
         * activity opens.
         */
        const val ALARM_NOTIFICATION_ID = 1001
    }

    /**
     * Sends a notification using arguments received from Flutter.
     *
     * The expected argument map supports:
     *
     * - `title`: Notification title.
     * - `description`: Notification body text.
     * - `notificationType`: `normal`, `silent`, or `fullScreen`.
     * - `notificationId`: Optional notification identifier.
     * - `autoCancel`: Whether the notification is dismissed when tapped.
     * - `ongoing`: Whether the notification should remain ongoing.
     * - `priority`: Notification priority.
     * - `category`: Android notification category.
     * - `playSound`: Whether notification sound should be enabled.
     * - `vibrate`: Whether notification vibration should be enabled.
     * - `alarmId`: Optional alarm identifier passed to a full-screen intent.
     *
     * @param arguments Arguments received from Flutter through the
     * MethodChannel.
     *
     * @throws IllegalArgumentException if the arguments are missing or the
     * required `title` argument is not provided.
     */
    fun send(
        arguments: Any?
    ) {
        val args =
            arguments as? Map<*, *>
                ?: throw IllegalArgumentException(
                    "Notification arguments are required"
                )

        val title =
            args["title"] as? String
                ?: throw IllegalArgumentException(
                    "title is required"
                )

        val description =
            args["description"] as? String
                ?: ""

        val type =
            args["notificationType"] as? String
                ?: "normal"

        val notificationId =
            (args["notificationId"] as? Number)
                ?.toInt()
                ?: DEFAULT_NOTIFICATION_ID

        val autoCancel =
            args["autoCancel"] as? Boolean
                ?: true

        val ongoing =
            args["ongoing"] as? Boolean
                ?: false

        val priority =
            args["priority"] as? String
                ?: "default"

        val category =
            args["category"] as? String
                ?: NotificationCompat.CATEGORY_STATUS

        val playSound =
            args["playSound"] as? Boolean
                ?: type != "silent"

        val vibrate =
            args["vibrate"] as? Boolean
                ?: type != "silent"

        val alarmId =
            (args["alarmId"] as? Number)
                ?.toInt()

        send(
            title = title,
            description = description,
            type = type,
            notificationId = notificationId,
            autoCancel = autoCancel,
            ongoing = ongoing,
            priority = priority,
            category = category,
            playSound = playSound,
            vibrate = vibrate,
            alarmId = alarmId
        )
    }

    /**
     * Removes all currently displayed notifications posted by this application.
     *
     * This is used when an alarm notification is triggered to ensure that
     * previously displayed StillAlive notifications do not remain visible
     * alongside the active alarm notification.
     */
    fun clearAllNotifications() {
        val manager =
            context.getSystemService(
                NotificationManager::class.java
            )

        manager.cancelAll()
    }

    /**
     * Sends the notification displayed when an Android alarm fires.
     *
     * Any existing notifications posted by this application are cleared before
     * the alarm notification is displayed. This prevents stale timer or other
     * application notifications from remaining visible while the alarm is
     * active.
     *
     * Alarm notifications are configured as ongoing, non-auto-cancelling,
     * high-priority alarm notifications with a full-screen intent targeting
     * [MainActivity].
     *
     * @param alarmId Unique identifier of the alarm that fired. The
     * identifier is passed to [MainActivity] through the full-screen Intent
     * so that Flutter can determine which alarm fired.
     */
    fun sendAlarm(
        alarmId: Int
    ) {
        send(
            title = context.getString(
                R.string.alarm_notification_title
            ),
            description = context.getString(
                R.string.alarm_notification_text
            ),
            type = "fullScreen",
            notificationId = ALARM_NOTIFICATION_ID,
            autoCancel = false,
            ongoing = true,
            priority = "max",
            category = NotificationCompat.CATEGORY_ALARM,
            playSound = true,
            vibrate = true,
            alarmId = alarmId
        )
    }

    /**
     * Constructs and posts a notification using the supplied configuration.
     *
     * The notification channel is selected according to [type]. Full-screen
     * notifications additionally receive a full-screen PendingIntent
     * targeting [MainActivity].
     *
     * @param title Notification title.
     * @param description Notification body text.
     * @param type Notification type. Supported values are `normal`,
     * `silent`, and `fullScreen`.
     * @param notificationId Android notification identifier.
     * @param autoCancel Whether the notification should automatically be
     * removed after the user taps it.
     * @param ongoing Whether the notification should be treated as ongoing.
     * @param priority Notification priority represented as a string.
     * @param category Android notification category.
     * @param playSound Whether the notification channel should use sound.
     * @param vibrate Whether the notification channel should enable vibration.
     * @param alarmId Optional alarm identifier passed to the full-screen
     * activity.
     */
    private fun send(
        title: String,
        description: String,
        type: String,
        notificationId: Int,
        autoCancel: Boolean,
        ongoing: Boolean,
        priority: String,
        category: String,
        playSound: Boolean,
        vibrate: Boolean,
        alarmId: Int?
    ) {
        clearAllNotifications()
        
        val channelId =
            getChannelId(type)

        createChannel(
            channelId = channelId,
            type = type,
            playSound = playSound,
            vibrate = vibrate
        )

        val builder =
            NotificationCompat.Builder(
                context,
                channelId
            )
                .setSmallIcon(
                    R.drawable.ic_notification
                )
                .setContentTitle(title)
                .setContentText(description)
                .setAutoCancel(autoCancel)
                .setOngoing(ongoing)
                .setCategory(category)
                .setPriority(
                    getPriority(priority)
                )

        if (type == "fullScreen") {
            addFullScreenIntent(
                builder = builder,
                notificationId = notificationId,
                alarmId = alarmId
            )
        }

        val manager =
            context.getSystemService(
                NotificationManager::class.java
            )

        manager.notify(
            notificationId,
            builder.build()
        )
    }

    /**
     * Adds a full-screen PendingIntent to a notification.
     *
     * The PendingIntent launches [MainActivity]. If an [alarmId] is
     * supplied, it is included in the Intent so that the activity can
     * identify the alarm that triggered the notification.
     *
     * @param builder Notification builder to which the full-screen intent
     * will be attached.
     * @param notificationId Notification identifier used as the PendingIntent
     * request code.
     * @param alarmId Optional alarm identifier passed to [MainActivity].
     */
    private fun addFullScreenIntent(
        builder: NotificationCompat.Builder,
        notificationId: Int,
        alarmId: Int?
    ) {
        val intent = Intent(
            context,
            MainActivity::class.java
        ).apply {
            flags =
                Intent.FLAG_ACTIVITY_NEW_TASK or
                Intent.FLAG_ACTIVITY_CLEAR_TOP or
                Intent.FLAG_ACTIVITY_SINGLE_TOP

            if (alarmId != null) {
                putExtra(
                    AlarmReceiver.EXTRA_ALARM_ID,
                    alarmId
                )
            }
        }

        val pendingIntent =
            PendingIntent.getActivity(
                context,
                notificationId,
                intent,
                PendingIntent.FLAG_UPDATE_CURRENT or
                PendingIntent.FLAG_IMMUTABLE
            )

        builder.setFullScreenIntent(
            pendingIntent,
            true
        )
    }

    /**
     * Determines the notification channel associated with a notification
     * type.
     *
     * @param type Notification type.
     * @return Channel identifier corresponding to the supplied type.
     */
    private fun getChannelId(
        type: String
    ): String {
        return when (type) {
            "fullScreen" ->
                FULL_SCREEN_CHANNEL_ID

            "silent" ->
                SILENT_CHANNEL_ID

            else ->
                NORMAL_CHANNEL_ID
        }
    }

    /**
     * Converts a human-readable priority string into the corresponding
     * [NotificationCompat] priority constant.
     *
     * Supported values are `min`, `low`, `default`, `high`, and `max`.
     *
     * @param priority Priority represented as a string.
     * @return Corresponding [NotificationCompat] priority constant.
     */
    private fun getPriority(
        priority: String
    ): Int {
        return when (priority.lowercase()) {
            "min" ->
                NotificationCompat.PRIORITY_MIN

            "low" ->
                NotificationCompat.PRIORITY_LOW

            "high" ->
                NotificationCompat.PRIORITY_HIGH

            "max" ->
                NotificationCompat.PRIORITY_MAX

            else ->
                NotificationCompat.PRIORITY_DEFAULT
        }
    }

    /**
     * Creates the Android notification channel required for the supplied
     * notification type.
     *
     * Notification channels are required on Android 8.0 (API 26) and later.
     * On earlier Android versions this method performs no action.
     *
     * The channel's importance is determined by the notification type.
     * Silent notifications use low importance, while normal and full-screen
     * notifications use high importance.
     *
     * @param channelId Identifier of the notification channel.
     * @param type Notification type used to determine channel importance.
     * @param playSound Whether the channel should play notification sounds.
     * @param vibrate Whether the channel should enable vibration.
     */
    private fun createChannel(
        channelId: String,
        type: String,
        playSound: Boolean,
        vibrate: Boolean
    ) {
        if (Build.VERSION.SDK_INT <
            Build.VERSION_CODES.O
        ) {
            return
        }

        val importance =
            when (type) {
                "silent" ->
                    NotificationManager.IMPORTANCE_LOW

                else ->
                    NotificationManager.IMPORTANCE_HIGH
            }

        val channel =
            NotificationChannel(
                channelId,
                getChannelName(type),
                importance
            )

        channel.enableVibration(
            vibrate
        )

        if (!playSound) {
            channel.setSound(
                null,
                null
            )
        }

        val manager =
            context.getSystemService(
                NotificationManager::class.java
            )

        manager.createNotificationChannel(
            channel
        )
    }

    /**
     * Returns the user-visible name of the notification channel associated
     * with a notification type.
     *
     * @param type Notification type.
     * @return Localized notification channel name.
     */
    private fun getChannelName(
        type: String
    ): String {
        return when (type) {
            "fullScreen" ->
                "Full-screen notifications"

            "silent" ->
                "Silent notifications"

            else ->
                "Notifications"
        }
    }
}
