// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'traits.dart';

/// Returns information about every supported integration.
Future<List<IntegrationInfo>> loadAllIntegrations() =>
    RustLib.instance.api.crateApiIntegrationsPublicTraitsLoadAllIntegrations();

/// Discovers destinations currently available to an account.
///
/// Discovery does NOT persist anything.
Future<List<MessageDestination>> discoverIntegrationDestinations({
  required String key,
  required String accountId,
}) => RustLib.instance.api
    .crateApiIntegrationsPublicTraitsDiscoverIntegrationDestinations(
      key: key,
      accountId: accountId,
    );

/// Authenticates an account with the external integration API, adds the
/// account to the integration configuration, and returns the newly created
/// account.
///
/// The returned account is persisted with no selected destinations.
///
/// The authentication request is performed by the integration
/// implementation.
///
/// # Arguments
///
/// * `key` - The integration identifier, for example, `"discord"` or
///   `"telegram"`.
/// * `credentials` - Credentials required to authenticate with the integration.
///   Must contain a non-empty `"token"` value.
///
/// # Errors
///
/// Returns an error if:
///
/// * `credentials` does not contain a non-empty `"token"`.
/// * The integration key is unknown.
/// * The integration configuration cannot be loaded.
/// * Authentication with the external API fails.
/// * The authenticated account cannot be added to the integration
///   configuration.
Future<IntegrationAccount> connectIntegrationAccount({
  required String key,
  required Map<String, String> credentials,
}) => RustLib.instance.api
    .crateApiIntegrationsPublicTraitsConnectIntegrationAccount(
      key: key,
      credentials: credentials,
    );

/// Deletes a connected integration account.
///
/// All destinations belonging to the account are removed together with
/// the account itself.
///
/// # Arguments
///
/// * `key` - The integration identifier (for example, `"discord"` or
///   `"telegram"`).
/// * `account_id` - The account identifier to remove.
///
/// # Errors
///
/// Returns an error if:
///
/// * The integration key is unknown.
/// * The integration configuration cannot be loaded.
/// * The updated configuration cannot be saved.
Future<void> deleteIntegrationAccount({
  required String key,
  required String accountId,
}) => RustLib.instance.api
    .crateApiIntegrationsPublicTraitsDeleteIntegrationAccount(
      key: key,
      accountId: accountId,
    );

/// Tests whether a selected destination can receive a message.
///
/// This checks the destination itself rather than merely checking whether
/// the integration account is connected.
///
/// # Arguments
///
/// * `key` - The integration identifier used to select the platform
///   (for example, `"discord"` or `"telegram"`).
/// * `account_id` - The account identifier.
/// * `destination_id` - The destination identifier to test.
///
/// # Returns
///
/// Returns an [`IntegrationTestResult`] containing:
///
/// * Whether the integration is connected.
/// * A human-readable status message.
///
/// # Errors
///
/// Returns an error if:
///
/// * The integration key is unknown.
/// * The integration configuration cannot be loaded.
/// * The integration test fails.
Future<DestinationTestResult> testIntegrationDestination({
  required String key,
  required String accountId,
  required String destinationId,
}) => RustLib.instance.api
    .crateApiIntegrationsPublicTraitsTestIntegrationDestination(
      key: key,
      accountId: accountId,
      destinationId: destinationId,
    );

/// Tests whether a selected account is accessible.
///
/// # Arguments
///
/// * `key` - The integration identifier used to select the platform
///   (for example, `"discord"` or `"telegram"`).
/// * `account_id` - The account identifier to test.
///
/// # Returns
///
/// Returns an [`IntegrationTestResult`] containing:
///
/// * Whether the integration is connected.
/// * A human-readable status message.
///
/// # Errors
///
/// Returns an error if:
///
/// * The integration key is unknown.
/// * The integration configuration cannot be loaded.
/// * The integration test fails.
Future<DestinationTestResult> testIntegrationAccount({
  required String key,
  required String accountId,
}) =>
    RustLib.instance.api.crateApiIntegrationsPublicTraitsTestIntegrationAccount(
      key: key,
      accountId: accountId,
    );

/// Sends a message to an explicitly selected destination.
///
/// The provider implementation is responsible for refusing to send to
/// destinations that aren't selected for the account.
///
/// # Arguments
///
/// * `key` - The integration identifier used to select the platform.
/// * `account_id` - The account identifier.
/// * `destination_id` - The destination identifier.
/// * `message` - The message content to send.
///
/// # Errors
///
/// Returns an error if:
///
/// * The integration key is unknown.
/// * The integration configuration cannot be loaded.
/// * Authentication fails.
/// * The destination cannot be reached.
/// * Sending the message fails.
Future<SentMessage> sendIntegrationMessage({
  required String key,
  required String accountId,
  required String destinationId,
  required String message,
}) =>
    RustLib.instance.api.crateApiIntegrationsPublicTraitsSendIntegrationMessage(
      key: key,
      accountId: accountId,
      destinationId: destinationId,
      message: message,
    );
