// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `load_config`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `accounts`, `add_account`, `authenticate_account`, `connected`, `connected`, `connected`, `discover_destinations`, `from_config`, `gradient`, `info`, `info`, `info`, `load`, `load`, `load`, `provider`, `remove_account`, `save_config`, `send_message`, `test_account`, `test_destination`, `title`

/// Kind of resource that can receive a message.
///
/// This deliberately describes the application's messaging model rather
/// than mirroring a provider's API types.
enum DestinationKind { directMessage, group, channel, serverChannel }

/// Result of testing a destination.
///
/// Contains whether the connection succeeded and an optional
/// human-readable message describing the result.
class DestinationTestResult {
  final bool canSend;
  final String message;

  const DestinationTestResult({required this.canSend, required this.message});

  @override
  int get hashCode => canSend.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DestinationTestResult &&
          runtimeType == other.runtimeType &&
          canSend == other.canSend &&
          message == other.message;
}

/// A connected account belonging to a messaging provider.
///
/// Only destinations explicitly selected by the user are persisted here.
class IntegrationAccount {
  final String id;
  final String name;
  final List<MessageDestination> destinations;
  final String? appId;

  const IntegrationAccount({
    required this.id,
    required this.name,
    required this.destinations,
    this.appId,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ destinations.hashCode ^ appId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntegrationAccount &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          destinations == other.destinations &&
          appId == other.appId;
}

/// Two-color linear gradient used to visually identify an integration.
///
/// Colors are encoded as Flutter-compatible ARGB values (0xAARRGGBB).
class IntegrationGradient {
  final int start;
  final int end;

  const IntegrationGradient({required this.start, required this.end});

  @override
  int get hashCode => start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntegrationGradient &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end;
}

/// Public integration metadata exposed to Flutter.
class IntegrationInfo {
  final String key;
  final String title;
  final IntegrationGradient gradient;
  final IntegrationProvider provider;
  final bool connected;
  final List<IntegrationAccount> accounts;

  const IntegrationInfo({
    required this.key,
    required this.title,
    required this.gradient,
    required this.provider,
    required this.connected,
    required this.accounts,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      title.hashCode ^
      gradient.hashCode ^
      provider.hashCode ^
      connected.hashCode ^
      accounts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntegrationInfo &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          title == other.title &&
          gradient == other.gradient &&
          provider == other.provider &&
          connected == other.connected &&
          accounts == other.accounts;
}

/// Supported messaging providers.
enum IntegrationProvider { discord, telegram }

/// A message destination discovered from a messaging provider.
///
/// `parent_id` and `parent_name` are optional metadata. For example, a
/// Discord server channel has its guild as its parent, while a DM does not.
class MessageDestination {
  final String id;
  final String name;
  final DestinationKind kind;
  final String? parentId;
  final String? parentName;

  const MessageDestination({
    required this.id,
    required this.name,
    required this.kind,
    this.parentId,
    this.parentName,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      parentId.hashCode ^
      parentName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDestination &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          kind == other.kind &&
          parentId == other.parentId &&
          parentName == other.parentName;
}

/// A message returned after sending.
class SentMessage {
  final IntegrationProvider provider;
  final String destinationId;
  final String? messageId;

  const SentMessage({
    required this.provider,
    required this.destinationId,
    this.messageId,
  });

  @override
  int get hashCode =>
      provider.hashCode ^ destinationId.hashCode ^ messageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SentMessage &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          destinationId == other.destinationId &&
          messageId == other.messageId;
}
