// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `load_config`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `channels`, `connected`, `connected`, `connected`, `delete`, `from_config`, `gradient`, `info`, `info`, `info`, `load`, `load`, `load`, `save_config`, `send`, `test`, `title`, `users`

/// Returns information about every supported integration.
///
/// Integrations that are not configured are still returned with empty
/// user and channel lists.
Future<List<IntegrationInfo>> loadAllIntegrations() =>
    RustLib.instance.api.crateApiIntegrationsTraitsLoadAllIntegrations();

/// Deletes a user or channel record from an integration configuration.
///
/// The target integration is loaded from the database, the matching record is
/// removed using the provided identifier, and the updated configuration is
/// persisted back to the database.
///
/// # Arguments
///
/// * `key` - The integration identifier (for example, `"discord"` or
///   `"telegram"`).
/// * `id` - The user or channel identifier to remove.
///
/// # Errors
///
/// Returns an error if:
///
/// * The integration key is unknown.
/// * The integration configuration cannot be loaded.
/// * The updated configuration cannot be saved.
Future<void> deleteIntegrationRecord({
  required String key,
  required String id,
}) => RustLib.instance.api.crateApiIntegrationsTraitsDeleteIntegrationRecord(
  key: key,
  id: id,
);

/// Tests whether an integration connection is available.
///
/// Loads the requested integration and executes its connection test logic.
/// The returned result contains both the connection status and a descriptive
/// message explaining the outcome.
///
/// # Arguments
///
/// * `key` - The integration identifier used to select the platform
///   (for example, `"discord"` or `"telegram"`).
/// * `id` - The platform-specific user or channel identifier to test.
///
/// # Returns
///
/// Returns an [`IntegrationTestResult`] containing:
///
/// * Whether the integration is connected.
/// * A human-readable status message.
///
/// # Errors
///
/// Returns an error if:
///
/// * The integration key is unknown.
/// * The integration configuration cannot be loaded.
/// * The integration test fails.
Future<IntegrationTestResult> testIntegrationConnection({
  required String key,
  required String id,
}) => RustLib.instance.api.crateApiIntegrationsTraitsTestIntegrationConnection(
  key: key,
  id: id,
);

/// Sends a message through an integration to a recipient.
///
/// The integration is loaded using the provided key and delegates the send
/// operation to the platform-specific implementation.
///
/// # Arguments
///
/// * `key` - The integration identifier used to select the platform.
/// * `recipient_id` - The platform-specific recipient identifier.
/// * `message` - The message content to send.
///
/// # Errors
///
/// Returns an error if:
///
/// * The integration key is unknown.
/// * The integration configuration cannot be loaded.
/// * Authentication fails.
/// * The recipient cannot be reached.
/// * Sending the message fails.
Future<void> sendIntegrationMessage({
  required String key,
  required String recipientId,
  required String message,
}) => RustLib.instance.api.crateApiIntegrationsTraitsSendIntegrationMessage(
  key: key,
  recipientId: recipientId,
  message: message,
);

/// Destination that can receive messages through an integration.
///
/// Discord channels belong to a guild, while platforms without
/// guilds may leave the guild fields empty.
class IntegrationChannel {
  final String? guildId;
  final String? guildName;
  final String channelId;
  final String channelName;

  const IntegrationChannel({
    this.guildId,
    this.guildName,
    required this.channelId,
    required this.channelName,
  });

  @override
  int get hashCode =>
      guildId.hashCode ^
      guildName.hashCode ^
      channelId.hashCode ^
      channelName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntegrationChannel &&
          runtimeType == other.runtimeType &&
          guildId == other.guildId &&
          guildName == other.guildName &&
          channelId == other.channelId &&
          channelName == other.channelName;
}

/// Two-color linear gradient used to visually identify an integration.
///
/// Colors are encoded as Flutter-compatible ARGB values (0xAARRGGBB).
class IntegrationGradient {
  final int start;
  final int end;

  const IntegrationGradient({required this.start, required this.end});

  @override
  int get hashCode => start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntegrationGradient &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end;
}

/// Summary of an integration exposed through Flutter Rust Bridge.
///
/// This structure contains metadata together with the connected users
/// and available message destinations required by the Flutter UI.
class IntegrationInfo {
  final String key;
  final String title;
  final IntegrationGradient gradient;
  final bool connected;
  final List<IntegrationUser> users;
  final List<IntegrationChannel> channels;

  const IntegrationInfo({
    required this.key,
    required this.title,
    required this.gradient,
    required this.connected,
    required this.users,
    required this.channels,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      title.hashCode ^
      gradient.hashCode ^
      connected.hashCode ^
      users.hashCode ^
      channels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntegrationInfo &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          title == other.title &&
          gradient == other.gradient &&
          connected == other.connected &&
          users == other.users &&
          channels == other.channels;
}

/// Result of testing an integration connection.
///
/// Contains whether the connection succeeded and an optional
/// human-readable message describing the result.
class IntegrationTestResult {
  final bool connected;
  final String message;

  const IntegrationTestResult({required this.connected, required this.message});

  @override
  int get hashCode => connected.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntegrationTestResult &&
          runtimeType == other.runtimeType &&
          connected == other.connected &&
          message == other.message;
}

/// User account connected to an integration.
///
/// For example, a Discord account or Telegram account authorized
/// to interact with the application.
class IntegrationUser {
  final String id;
  final String username;

  const IntegrationUser({required this.id, required this.username});

  @override
  int get hashCode => id.hashCode ^ username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntegrationUser &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          username == other.username;
}
