// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Export a complete application backup as a ZIP archive in memory.
///
/// The generated backup contains:
///
/// - the SQLite database
/// - a metadata file
///
/// The ZIP archive is returned as raw bytes (`Vec<u8>`), making it
/// platform-independent.
///
/// # Export procedure
///
/// 1. Perform WAL checkpoint to ensure DB consistency.
/// 2. Read database file into memory.
/// 3. Generate metadata JSON in memory.
/// 4. Create ZIP archive in memory.
/// 5. Return ZIP as `Vec<u8>`.
///
/// The database connection remains open throughout the export.
///
/// # Arguments
///
/// * `app_version` - Application version.
///
/// # Returns
///
/// A `Vec<u8>` containing the full ZIP archive.
///
/// # Errors
///
/// Returns an error if:
///
/// - WAL checkpoint fails
/// - database file cannot be read
/// - metadata cannot be generated
/// - ZIP creation fails
///
/// # Notes
///
/// - No files are written to storage.
/// - Entire ZIP is held in memory.
Future<Uint8List> exportBackup({required String appVersion}) => RustLib.instance.api.crateApiBackupExportBackup(appVersion: appVersion);

/// Import an application backup from a ZIP archive.
///
/// # Import procedure:
///
/// 1. Extract ZIP archive into memory.
/// 2. Extract `metadata.json` and validate it.
/// 3. Validate backup format and compatibility.
/// 4. Extract database file into memory.
/// 5. Close current database connection.
/// 6. Overwrite existing database file.
/// 7. Reopen database.
///
/// # Arguments
///
/// - `zip_path` - Path to the backup ZIP archive.
/// - `app_version` - Current application version.
///
/// # Errors
///
/// Returns an error if:
///
/// - the ZIP archive is invalid
/// - required files are missing
/// - metadata validation fails
/// - the database cannot be replaced
Future<void> importBackup({required String zipPath, required String appVersion}) =>
    RustLib.instance.api.crateApiBackupImportBackup(zipPath: zipPath, appVersion: appVersion);
