import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';
import 'package:qr_flutter/qr_flutter.dart';

import '../../../data/all.dart';
import '../../widgets/primitives.dart';

/// A screen that displays a QR code for sharing an integration destination.
///
/// The QR code contains encoded integration data generated by
/// [IntegrationRow]. The screen also displays the integration title and
/// channel name associated with the QR code.
class QrCodeScreen extends StatefulWidget {
  const QrCodeScreen({super.key, required this.integrationTitle, required this.accountName, required this.qrData});

  final String integrationTitle;
  final String accountName;
  final String qrData;

  @override
  State<QrCodeScreen> createState() => _QrCodeScreenState();
}

/// State implementation for [QrCodeScreen].
class _QrCodeScreenState extends State<QrCodeScreen> {
  @override
  Widget build(BuildContext context) {
    ColorScheme scheme = Theme.of(context).colorScheme;
    AppLocalizations local = AppLocalizations.of(context)!;

    return ScreenBase(
      header: AppHeader(
        title: local.translate("qr_display.title"),
        left: CircleIconButton(icon: LucideIcons.chevronLeft, onTap: () => Navigator.of(context).pop()),
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Stack(
            alignment: Alignment.center,
            children: [
              DecoratedBox(
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(AppRadius.xxl),
                  boxShadow: [BoxShadow(color: scheme.secondary.withAlpha(128), blurRadius: 60, spreadRadius: -20, offset: Offset(0, 20))],
                ),
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(AppRadius.xxl),
                  child: QrImageView(
                    data: widget.qrData,
                    size: 300,
                    backgroundColor: (scheme.brightness == Brightness.dark) ? Colors.black : Colors.white,
                    padding: const EdgeInsets.all(AppSpacing.xxl),
                    errorCorrectionLevel: QrErrorCorrectLevel.H,
                    eyeStyle: QrEyeStyle(eyeShape: QrEyeShape.square, color: (scheme.brightness == Brightness.light) ? Colors.black : Colors.white),
                    dataModuleStyle: QrDataModuleStyle(
                      dataModuleShape: QrDataModuleShape.square,
                      color: (scheme.brightness == Brightness.light) ? Colors.black : Colors.white,
                    ),
                  ),
                ),
              ),

              Container(
                width: 60,
                height: 60,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(AppRadius.pill),
                  color: (scheme.brightness == Brightness.dark) ? Colors.black : Colors.white,
                ),
                child: Icon(LucideIcons.shield, size: 32, color: (scheme.brightness == Brightness.light) ? Colors.black : Colors.white),
              ),
            ],
          ),

          const SizedBox(height: AppSpacing.xl),
          Column(
            children: [
              Text(widget.accountName, style: AppText.sectionLabel(scheme).copyWith(letterSpacing: 2)),
              const SizedBox(height: AppSpacing.xxs),
              Text(widget.integrationTitle, style: AppText.h2(scheme).copyWith(fontSize: AppSpacing.xl, letterSpacing: 4)),
            ],
          ),
        ],
      ),
    );
  }
}
