// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'run.dart';
import 'state.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Reconciles the persisted timer state with the current timestamp.
///
/// The timer is loaded from persistent storage and its state is evaluated
/// against `now_ms`. If the calculated state differs from the persisted state,
/// the updated state is written back to the database.
///
/// # Arguments
///
/// * `now_ms` - Current timestamp in milliseconds since the Unix epoch.
///
/// # Returns
///
/// Returns the active timer if it can be loaded and reconciled successfully.
/// Returns `None` if loading or updating the timer fails.
Future<ActiveTimer?> reconcileActiveTimer({required PlatformInt64 nowMs}) =>
    RustLib.instance.api.crateApiTimerActiveTimerReconcileActiveTimer(
      nowMs: nowMs,
    );

/// Generates a unique identifier for a new timer.
///
/// # Returns
///
/// Returns a timer identifier based on the the first unused timer
/// identifier.
/// Returns `None` if the number of timers cannot be retrieved.
Future<String?> getUniqueTimerId() =>
    RustLib.instance.api.crateApiTimerActiveTimerGetUniqueTimerId();

/// Creates a new timer from the given configuration.
///
/// # Arguments
///
/// * `config` - Configuration for the new timer.
///
/// # Errors
///
/// Returns an error if the new timer configuration cannot be
/// persisted to the database.
Future<void> createTimer({required TimerConfig config}) =>
    RustLib.instance.api.crateApiTimerActiveTimerCreateTimer(config: config);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ActiveTimer>>
abstract class ActiveTimer implements RustOpaqueInterface {
  TimerConfig get config;

  String get key;

  TimerRun get run;

  set config(TimerConfig config);

  set key(String key);

  set run(TimerRun run);

  /// Cancels the current timer run.
  ///
  /// A running timer is transitioned to `Cancelled`. An expired timer is
  /// transitioned to `Completed`. Paused, warning, cancelled, and completed
  /// timers are left unchanged.
  ///
  /// If password protection is enabled, `password_verified` must be `true`.
  ///
  /// The resulting state is persisted before the in-memory run is updated.
  ///
  /// # Arguments
  ///
  /// * `now_ms` - Current timestamp in milliseconds since the Unix epoch.
  /// * `password_verified` - Whether the caller has successfully verified
  ///   the timer's password.
  ///
  /// # Errors
  ///
  /// Returns an error if password verification is required but has not been
  /// completed, or if the resulting timer state cannot be persisted.
  Future<void> cancelTimerRun({
    required PlatformInt64 nowMs,
    required bool passwordVerified,
  });

  /// Deletes a timer.
  ///
  /// `timer0` cannot be deleted. If deleting the timer also removes the
  /// currently persisted timer run through the database cascade and no
  /// timer run remains, a replacement run is created for a remaining timer.
  ///
  /// When multiple timers remain, a random timer is selected. If only
  /// `timer0` remains, `timer0` is used.
  ///
  /// The returned [`ActiveTimer`] represents the timer that is active after
  /// the deletion.
  ///
  /// # Arguments
  ///
  /// * `key` - Identifier of the timer to delete.
  /// * `now_ms` - Current timestamp in milliseconds since the Unix epoch.
  ///
  /// # Errors
  ///
  /// Returns an error if `timer0` is requested, the timer cannot be deleted,
  /// no timers remain, or the replacement timer run cannot be created.
  Future<void> deleteTimer({required String key, required PlatformInt64 nowMs});

  /// Pauses the currently running timer.
  ///
  /// A timer in the `Running` or `Warning` state can be paused. A timer that
  /// is already paused is left unchanged.
  ///
  /// If password protection is enabled, `password_verified` must be `true`.
  ///
  /// The new state is persisted before the in-memory run is updated.
  ///
  /// # Arguments
  ///
  /// * `now_ms` - Current timestamp in milliseconds since the Unix epoch.
  /// * `password_verified` - Whether the caller has successfully verified
  ///   the timer's password.
  ///
  /// # Errors
  ///
  /// Returns an error if password verification is required but has not been
  /// completed, if the timer cannot be paused in its current state, or if
  /// the updated timer state cannot be persisted.
  Future<void> pauseTimerRun({
    required PlatformInt64 nowMs,
    required bool passwordVerified,
  });

  /// Replaces the currently active timer with a new timer.
  ///
  /// The new timer is created using the provided key and configuration. Its
  /// initial run is marked as `Completed`, with its timestamps calculated from
  /// the provided current time and configured duration. If a grace period is
  /// configured, it is stored as part of the new run.
  ///
  /// The new timer run and timer configuration are persisted to the database
  /// before the in-memory timer is updated.
  ///
  /// # Arguments
  ///
  /// * `key` - Unique key identifying the new timer.
  /// * `config` - Configuration for the new timer.
  /// * `now_ms` - Current timestamp in milliseconds since the Unix epoch.
  ///
  /// # Errors
  ///
  /// Returns an error if the new timer run or timer configuration cannot be
  /// persisted to the database.
  Future<void> replaceActiveTimer({
    required String key,
    required TimerConfig config,
    required PlatformInt64 nowMs,
  });

  /// Resumes a paused timer.
  ///
  /// The time elapsed while the timer was paused is added to the original
  /// start and expiration timestamps so that the remaining timer duration
  /// is preserved.
  ///
  /// The updated run is persisted before the in-memory run is updated.
  ///
  /// # Arguments
  ///
  /// * `now_ms` - Current timestamp in milliseconds since the Unix epoch.
  ///
  /// # Errors
  ///
  /// Returns an error if the timer is not paused, if its pause timestamp is
  /// missing, or if the updated timer state cannot be persisted.
  Future<void> resumeTimerRun({required PlatformInt64 nowMs});

  /// Starts a new timer run.
  ///
  /// The timer's expiration time is calculated from the configured duration.
  /// If a grace period is configured, it is stored as part of the new run.
  ///
  /// The updated timer run is also persisted to the database.
  ///
  /// # Arguments
  ///
  /// * `now_ms` - Current timestamp in milliseconds since the Unix epoch.
  ///
  /// # Errors
  ///
  /// Returns an error if the timer run cannot be persisted to the database.
  Future<void> startTimerRun({required PlatformInt64 nowMs});

  /// Updates the current timer run's state based on the current time.
  ///
  /// The timer's state is evaluated using its current timestamps and the
  /// provided time. If the evaluated state differs from the current state,
  /// the updated state is persisted to the database before the in-memory
  /// run is updated.
  ///
  /// If the evaluated state is unchanged, no database update is performed.
  ///
  /// # Arguments
  ///
  /// * `now_ms` - Current timestamp in milliseconds since the Unix epoch.
  ///
  /// # Errors
  ///
  /// Returns an error if the updated timer state cannot be persisted to the
  /// database.
  Future<void> updateRunState({required PlatformInt64 nowMs});
}
