// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TimerConfig>>
abstract class TimerConfig implements RustOpaqueInterface {
  bool get audioRecordingEnabled;

  List<Contact> get contacts;

  String get createdAt;

  List<String> get customEmail;

  List<String> get customSms;

  PlatformInt64 get durationSecs;

  PlatformInt64? get gracePeriodSecs;

  TimerIntegrations get integrations;

  PlatformInt64? get locationCollectionIntervalSecs;

  bool get locationSharingEnabled;

  String? get message;

  String get name;

  String? get passwordHash;

  bool get passwordProtected;

  bool get routeSharingEnabled;

  String get updatedAt;

  set audioRecordingEnabled(bool audioRecordingEnabled);

  set contacts(List<Contact> contacts);

  set createdAt(String createdAt);

  set customEmail(List<String> customEmail);

  set customSms(List<String> customSms);

  set durationSecs(PlatformInt64 durationSecs);

  set gracePeriodSecs(PlatformInt64? gracePeriodSecs);

  set integrations(TimerIntegrations integrations);

  set locationCollectionIntervalSecs(
    PlatformInt64? locationCollectionIntervalSecs,
  );

  set locationSharingEnabled(bool locationSharingEnabled);

  set message(String? message);

  set name(String name);

  set passwordHash(String? passwordHash);

  set passwordProtected(bool passwordProtected);

  set routeSharingEnabled(bool routeSharingEnabled);

  set updatedAt(String updatedAt);

  /// Creates a new timer configuration from the given fields.
  factory TimerConfig({
    required String name,
    required PlatformInt64 durationSecs,
    PlatformInt64? gracePeriodSecs,
    required bool passwordProtected,
    String? passwordHash,
    required bool locationSharingEnabled,
    required bool routeSharingEnabled,
    PlatformInt64? locationCollectionIntervalSecs,
    required bool audioRecordingEnabled,
    required List<Contact> contacts,
    required List<String> customSms,
    required List<String> customEmail,
    required TimerIntegrations integrations,
    String? message,
    required String createdAt,
    required String updatedAt,
  }) => RustLib.instance.api.crateApiTimerConfigTimerConfigNew(
    name: name,
    durationSecs: durationSecs,
    gracePeriodSecs: gracePeriodSecs,
    passwordProtected: passwordProtected,
    passwordHash: passwordHash,
    locationSharingEnabled: locationSharingEnabled,
    routeSharingEnabled: routeSharingEnabled,
    locationCollectionIntervalSecs: locationCollectionIntervalSecs,
    audioRecordingEnabled: audioRecordingEnabled,
    contacts: contacts,
    customSms: customSms,
    customEmail: customEmail,
    integrations: integrations,
    message: message,
    createdAt: createdAt,
    updatedAt: updatedAt,
  );
}

/// Represents a contact associated with a timer.
class Contact {
  /// Unique identifier of the contact.
  final String id;

  /// SMS destinations associated with the contact.
  final List<String> sms;

  /// Email destinations associated with the contact.
  final List<String> email;

  const Contact({required this.id, required this.sms, required this.email});

  @override
  int get hashCode => id.hashCode ^ sms.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Contact &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sms == other.sms &&
          email == other.email;
}

/// Configuration for a specific external integration.
class TimerIntegration {
  /// Accounts configured for this integration.
  final List<TimerIntegrationAccount> accounts;

  const TimerIntegration({required this.accounts});

  @override
  int get hashCode => accounts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimerIntegration &&
          runtimeType == other.runtimeType &&
          accounts == other.accounts;
}

/// Represents an account configured for an external integration.
class TimerIntegrationAccount {
  /// Unique identifier of the integration account.
  final String id;

  /// Destinations associated with the account.
  ///
  /// The meaning of a destination depends on the integration, such as a
  /// Discord channel or Telegram chat.
  final List<String> destinations;

  const TimerIntegrationAccount({required this.id, required this.destinations});

  @override
  int get hashCode => id.hashCode ^ destinations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimerIntegrationAccount &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          destinations == other.destinations;
}

/// Contains the external integrations configured for a timer.
class TimerIntegrations {
  /// Discord integration configuration.
  final TimerIntegration discord;

  /// Telegram integration configuration.
  final TimerIntegration telegram;

  const TimerIntegrations({required this.discord, required this.telegram});

  @override
  int get hashCode => discord.hashCode ^ telegram.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimerIntegrations &&
          runtimeType == other.runtimeType &&
          discord == other.discord &&
          telegram == other.telegram;
}
