// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'state.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Represents a persisted execution of a timer.
///
/// A [`TimerRun`] contains the timing information and current state for a
/// particular timer instance. It is persisted separately from the timer's
/// configuration.
class TimerRun {
  /// Identifier of the timer associated with this run.
  final String timerId;

  /// Current lifecycle state of the timer run.
  final TimerState state;

  /// Timestamp, in milliseconds since the Unix epoch, at which the run started.
  final PlatformInt64 startedAtMs;

  /// Timestamp, in milliseconds since the Unix epoch, at which the run expires.
  final PlatformInt64 expiresAtMs;

  /// Optional grace-period duration, in milliseconds, after the expiration time.
  final PlatformInt64? warningDurationMs;

  /// Timestamp, in milliseconds since the Unix epoch, at which the run was paused.
  ///
  /// This is `None` when the timer has not been paused or has been resumed.
  final PlatformInt64? pausedAtMs;

  const TimerRun({
    required this.timerId,
    required this.state,
    required this.startedAtMs,
    required this.expiresAtMs,
    this.warningDurationMs,
    this.pausedAtMs,
  });

  /// Evaluates the timer's state at the specified timestamp.
  ///
  /// Terminal and paused states are returned unchanged. For an active timer,
  /// the current state is calculated using its expiration time and optional
  /// grace period.
  ///
  /// # Arguments
  ///
  /// * `now_ms` - Current timestamp in milliseconds since the Unix epoch.
  ///
  /// # Returns
  ///
  /// The state the timer should currently have at `now_ms`.
  Future<TimerState> evaluateState({required PlatformInt64 nowMs}) =>
      RustLib.instance.api.crateApiTimerRunTimerRunEvaluateState(that: this, nowMs: nowMs);

  /// Returns whether the timer is currently active.
  ///
  /// A timer is considered active while it is [`TimerState::Running`].
  Future<bool> isActive() => RustLib.instance.api.crateApiTimerRunTimerRunIsActive(that: this);

  @override
  int get hashCode =>
      timerId.hashCode ^ state.hashCode ^ startedAtMs.hashCode ^ expiresAtMs.hashCode ^ warningDurationMs.hashCode ^ pausedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimerRun &&
          runtimeType == other.runtimeType &&
          timerId == other.timerId &&
          state == other.state &&
          startedAtMs == other.startedAtMs &&
          expiresAtMs == other.expiresAtMs &&
          warningDurationMs == other.warningDurationMs &&
          pausedAtMs == other.pausedAtMs;
}
