// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Represents the current lifecycle state of a timer run.
enum TimerState {
  /// The timer is actively counting down.
  running,

  /// The timer is temporarily stopped and can be resumed.
  paused,

  /// The timer was manually cancelled before completion.
  cancelled,

  /// The timer exceeded its expiration time, including any configured grace period.
  expired,

  /// The timer has passed its expiration time but is still within its grace period.
  warning,

  /// The timer has reached a terminal completed state.
  completed;

  /// Returns the string representation used when persisting the state.
  Future<void> asStr() => RustLib.instance.api.crateApiTimerStateTimerStateAsStr(that: this);

  /// Converts a persisted timer state string into a [`TimerState`].
  ///
  /// # Errors
  ///
  /// Returns an error if `value` does not match a known timer state.
  static Future<TimerState> stateFromStr({required String value}) => RustLib.instance.api.crateApiTimerStateTimerStateStateFromStr(value: value);
}
